### ISSUE TITLE
您好，请问一下手眼标定中，camera params json file和rvec txt file的格式是怎么样的？

### ISSUE THREAD

**Issue by liangyijian1** [zacario-li/CalibrationTool#1]

**Comment by zacario-li** [comment]
1. The app can automatically generate a camera parameters JSON file in the 'mono/stereo' tab. You can also create it yourself using a set of checkerboard images.
2. For the 'rvec text file' format, I recommend using the quaternion + translation format, as described in the [readme.md](https://github.com/zacario-li/CalibrationTool#usage).

**Comment by liangyijian1** [comment]
> 1. The app can automatically generate a camera parameters JSON file in the 'mono/stereo' tab. You can also create it yourself using a set of checkerboard images.
> 2. For the 'rvec text file' format, I recommend using the quaternion + translation format, as described in the [readme.md](https://github.com/zacario-li/CalibrationTool#usage).

Thank you, but I have a new problem.CAL_DATA_SIZE_NOT_MATCH error has occurred.
Here is the console output:
2024-10-10 14:09:56.361 | DEBUG    | utils.calib:wrapper:55 - calculate_img_rt_parallel took 26.088627099990845 seconds
2024-10-10 14:09:56.373 | WARNING  | ui.tabHandEye:do_axxb_calib:663 - g2n size not match b2c

**Comment by liangyijian1** [comment]
> > 1. The app can automatically generate a camera parameters JSON file in the 'mono/stereo' tab. You can also create it yourself using a set of checkerboard images.
> > 2. For the 'rvec text file' format, I recommend using the quaternion + translation format, as described in the [readme.md](https://github.com/zacario-li/CalibrationTool#usage).
> 
> Thank you, but I have a new problem.CAL_DATA_SIZE_NOT_MATCH error has occurred. Here is the console output: 2024-10-10 14:09:56.361 | DEBUG | utils.calib:wrapper:55 - calculate_img_rt_parallel took 26.088627099990845 seconds 2024-10-10 14:09:56.373 | WARNING | ui.tabHandEye:do_axxb_calib:663 - g2n size not match b2c

I forgot to add the header in the csv file.

**Comment by KKharry04** [comment]
sorry,I have the same problem,but I'm already add the header in file.
