### ISSUE TITLE
> > 1. The app can automatically generate a camera parameters JSON file in the 'mono/stereo' tab. You can also create it yourself using a set of checkerboard images.

### ISSUE THREAD

**Issue by KKharry04** [zacario-li/CalibrationTool#2]
> > 1. The app can automatically generate a camera parameters JSON file in the 'mono/stereo' tab. You can also create it yourself using a set of checkerboard images.
> > 2. For the 'rvec text file' format, I recommend using the quaternion + translation format, as described in the [readme.md](https://github.com/zacario-li/CalibrationTool#usage).
> 
> Thank you, but I have a new problem.CAL_DATA_SIZE_NOT_MATCH error has occurred. Here is the console output: 2024-10-10 14:09:56.361 | DEBUG | utils.calib:wrapper:55 - calculate_img_rt_parallel took 26.088627099990845 seconds 2024-10-10 14:09:56.373 | WARNING | ui.tabHandEye:do_axxb_calib:663 - g2n size not match b2c

I forgot to add the header in the csv file.

_Originally posted by @liangyijian1 in https://github.com/zacario-li/CalibrationTool/issues/1#issuecomment-2404182579_

**Comment by KKharry04** [comment]
你好，请问这个具体的格式是什么样的，我添加了表头还是不对

**Comment by zacario-li** [comment]
> 你好，请问这个具体的格式是什么样的，我添加了表头还是不对

Could you share me your csv file?Then I can check it.

**Comment by KKharry04** [comment]
This is the csv file which I used in yours app.Looking forward to your answer

**Comment by zacario-li** [comment]
> This is the csv file which I used in yours app.Looking forward to your answer Message ID: ***@***.***&gt;

Where's the file?I can't see it.
Here I attached my csv file for your ref.
[quat.csv](https://github.com/user-attachments/files/17634609/quat.csv)
